### ISSUE TITLE
Using the PT version, the article's image is not displayed correctly.

### ISSUE THREAD

**Issue by filipemanuelofs** [prine/WikiApiObjectiveC#5]
Here's my code:

``` objective-c
- (void)viewDidLoad {
    [super viewDidLoad];

    WikipediaHelper *wikiHelper = [[WikipediaHelper alloc] init];
    wikiHelper.apiUrl = @"http://pt.wikipedia.org";
    wikiHelper.delegate = self;

    NSString *searchWord = @"Recife";

    [wikiHelper fetchArticle:searchWord];
}



- (void)dataLoaded:(NSString *)htmlPage withUrlMainImage:(NSString *)urlMainImage {
    if(![urlMainImage isEqualToString:@""]) {
        NSData *imageData = [[NSData alloc] initWithContentsOfURL: [NSURL URLWithString: urlMainImage]];
        UIImage *image = [UIImage imageWithData:imageData];
        imageBrasilia.image = image;
    }

}
```

![screen shot 2015-07-09 at 21 21 24](https://cloud.githubusercontent.com/assets/1047292/8609823/a211715c-2680-11e5-8c06-994256d87947.png)

**Comment by prine** [comment]
Yeah the problem is that it's kind of hard to find the main image of the article. The main image never has the same name so that's why I had to work with a blacklist of image paths which are filtered out. Looks like your article contains an image which isnt on the blacklist. You can add this imagepath to the blacklist and then it should hopefully work. You can commit your changes on the blacklist as pull request and i will merge into the main code.
